FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build

COPY pom.xml ./pom.xml
COPY microservice-cargo/pom.xml ./microservice-cargo/pom.xml
COPY microservice-cargo/src ./microservice-cargo/src

RUN mvn -N install -DskipTests

WORKDIR /build/microservice-cargo
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build /build/microservice-cargo/target/microservice-cargo-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 9080

ENTRYPOINT ["java", "-jar", "app.jar"]