server:
  port: 9080

spring:
  application:
    name: msvc-cargo
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

eureka:
  instance:
    hostname: ${CARGO_HOSTNAME:msvc-cargo.onrender.com}
    prefer-ip-address: false
    non-secure-port: 80
    secure-port: 443
  client:
    service-url:
      defaultZone: https://${EUREKA_HOSTNAME:msvc-eureka.onrender.com}/eureka/