server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:msvc-eureka.onrender.com}
    prefer-ip-address: false
    non-secure-port: 80
    secure-port: 443
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://${EUREKA_HOSTNAME:msvc-eureka.onrender.com}/eureka/
  server:
    enable-self-preservation: false