server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:msvc-eureka.onrender.com}
    non-secure-port: 80
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: https://${EUREKA_HOSTNAME:msvc-eureka.onrender.com}/eureka/