server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedOrigins:
              - "http://localhost:4200"
              - "https://tu-frontend.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cargo
          uri: lb://msvc-cargo
          predicates:
            - Path=/api/cargo/**
        - id: security
          uri: lb://msvc-security
          predicates:
            - Path=/api/auth/**
eureka:
  instance:
    hostname: ${GATEWAY_HOSTNAME:app-gateway.azurewebsites.net}
    prefer-ip-address: false
    non-secure-port: 80
    secure-port: 443
  client:
    service-url:
      defaultZone: https://${EUREKA_HOSTNAME:app-eureka-server.azurewebsites.net}/eureka/